harvest_doi_records:
  cron: "0 23 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31 * *"
  class: "Tobias::ScheduledHarvest"
  queue: harvest

scrape_doaj:
  cron: "0 23 * * 6"
  class: "Tobias::DoajScrapeTask"
  queue: harvest

index_second_core:
  cron: "0 23 * * 0"
  class: "Tobias::ScheduledIndex"
  queue: index
  